obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.39, 0.22], [0.39, -0.22], [-0.31, -0.22], [-0.31, 0.22]]
inflation_radius: 0.5

#map_type: costmap

#expected_update_rate: 0.2
transform_tolerance: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: /scan_front, marking: true, clearing: true, min_obstacle_height: -0.10}
