initposition:       [0.011, 0.011, -0.1, 0.023, 0.12 ]

zeroposition:       [2.9496, 1.13446, -2.54818, 1.78896, 2.92345]

pregrasp_front_init: [2.9496, 1.18826, -1.17518, 3.15417, 2.9234]
pregrasp_front:      [2.9496, 1.53785, -1.17518, 3.15417, 2.9234]

pregrasp_back_init: [2.9496, 1.18826, -3.1595, 0.14564, 2.9234]
pregrasp_back:      [2.9496, 0.5475,  -3.1595, 0.14564, 2.9234]

pregrasp_right_init: [4.5204, 1.18826, -1.17518, 3.15417, 2.9234]
pregrasp_right:      [4.5204, 1.53785, -1.17518, 3.15417, 2.9234]

pregrasp_left_init: [1.3788, 1.18826, -1.17518, 3.15417, 2.9234]
pregrasp_left:      [1.3788, 1.53785, -1.17518, 3.15417, 2.9234]

kinect_right_init: [4.5204, 1.18826, -1.17518, 3.15417, 2.9234]
kinect_right:      [5.4, 2.5, -2.5, 1.5, 2.9234]

kinect_left_init: [1.3788, 1.18826, -1.17518, 3.15417, 2.9234]
kinect_left:      [0.4, 2.5, -2.5, 1.5, 2.9234]

flatposition: [2.9288059044017993, 0.0101, -0.027, 2.7123644907202462, 3.0723090453006798]


